# Generated by Django 5.0.7 on 2026-03-15 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_question_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.DeleteModel(
            name='AssessmentQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
