# Generated by Django 5.0.7 on 2026-03-16 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_questionoption_question_and_more'),
        ('jobs', '0012_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
