# Generated by Django 5.0.7 on 2026-03-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_assessmenttemplate_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=10),
        ),
    ]
