# Generated by Django 5.0.7 on 2026-03-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidateprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
