# Generated by Django 5.0.7 on 2026-02-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('station', models.CharField(max_length=100)),
                ('description', models.TextField(default='write some thing about job')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=400)),
                ('shift', models.CharField(max_length=50)),
            ],
        ),
    ]
