# Generated by Django 5.0.7 on 2026-03-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='companyEmail',
            field=models.EmailField(default='comapany Email', max_length=254),
        ),
    ]
