# Generated by Django 5.0.7 on 2026-03-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='companyEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
