# Generated by Django 5.0.7 on 2026-03-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
